




.build/attiny45/src/noisemaker_sketch.cpp : src/noisemaker_sketch.ino
	@mkdir -p .build/attiny45/src
	@echo [93msrc/noisemaker_sketch.ino[0m
	@/usr/local/bin/ino preproc  -o $@ $^


all : .build/attiny45/src/noisemaker_sketch.cpp
	@true

